### PR TITLE
turnserver: add support for CNAMEs on the Snikket domain

### PR DESCRIPTION
**Pull request by horazont**
I have that on my test domain and I think this should be a supported
case. In non-APEX cases, that would be a valid way to use the hosting
service.

### CODE REVIEW

**Comment by Zash** [comment]
Doesn't [net.dns do this itself](https://hg.prosody.im/trunk/rev/45222bfb206f)?

**Comment by horazont** [comment]
@Zash It didn't work for me, if it attempts to. Needs more debugging, but this diff fixes a real issue with my CNAME. CNAMEs meh.

**Comment by Zash** [comment]
Ah, `net.dns` has a filter that prevents caching of records from outside the queried zone, so if you have `foo.example.com IN CNAME bar.example` then an A record for the CNAME target won't be cached or returned. Curious that nobody has had problems with that...

**Comment by horazont** [comment]
In my case, it was:

```
snikket-test.$foo.dedyn.io CNAME $foo.dedyn.io.
```

So not exactly "outside the queried zone".

**Comment by Zash** [comment]
Something something [1381b2071c2e](https://hg.prosody.im/trunk/rev/1381b2071c2e) has been reverted back and forth a bit. Not entirely sure I understand what's going on there. Did I ever mention how nice it is to just use a library for this? :)

**Pull request merged**
