### PR TITLE
docs: reverse_proxy: Add guide for Caddy

### PR DESCRIPTION
**Pull request by Rijul-A**
Now that mholt/caddy-l4#33 has been merged, Caddy can be used as a reverse proxy for Snikket with all the features of `sslh`, _and_ forwarding port 80 to Snikket's 5080.

### CODE REVIEW

**Comment by mwild1** [comment]
Thanks for this! And your contribution to Caddy :)

I note that your changes don't appear to be in a release yet. It might be worth noting that, or holding off on merging this until they are (but even then it should probably clarify what Caddy version is required).

Would love for someone to test this (@turguenev? :slightly_smiling_face: ) and report how they get on.

**Comment by Rijul-A** [comment]
> I note that your changes don't appear to be in a release yet. It might be worth noting that, or holding off on merging this until they are (but even then it should probably clarify what Caddy version is required).

Caddy's plugins do not need a release; they are simply based on the `master` branch. A build made right now includes the modules `layer4.matchers.xmpp` and `tls.handshake_match.alpn`
```bash
$ wget https://github.com/caddyserver/xcaddy/releases/download/v0.2.0/xcaddy_0.2.0_linux_amd64.tar.gz
$ tar -xvzf xcaddy_0.2.0_linux_amd64.tar.gz
$ ./xcaddy build --with github.com/mholt/caddy-l4
$ ./caddy list-modules
admin.api.load
admin.api.metrics
admin.api.reverse_proxy
caddy.adapters.caddyfile
caddy.config_loaders.http
caddy.listeners.tls
caddy.logging.encoders.console
caddy.logging.encoders.filter
caddy.logging.encoders.filter.delete
caddy.logging.encoders.filter.ip_mask
caddy.logging.encoders.filter.replace
caddy.logging.encoders.json
caddy.logging.encoders.single_field
caddy.logging.writers.discard
caddy.logging.writers.file
caddy.logging.writers.net
caddy.logging.writers.stderr
caddy.logging.writers.stdout
caddy.storage.file_system
http
http.authentication.hashes.bcrypt
http.authentication.hashes.scrypt
http.authentication.providers.http_basic
http.encoders.gzip
http.encoders.zstd
http.handlers.acme_server
http.handlers.authentication
http.handlers.encode
http.handlers.error
http.handlers.file_server
http.handlers.headers
http.handlers.map
http.handlers.metrics
http.handlers.push
http.handlers.request_body
http.handlers.reverse_proxy
http.handlers.rewrite
http.handlers.static_response
http.handlers.subroute
http.handlers.templates
http.handlers.vars
http.matchers.expression
http.matchers.file
http.matchers.header
http.matchers.header_regexp
http.matchers.host
http.matchers.method
http.matchers.not
http.matchers.path
http.matchers.path_regexp
http.matchers.protocol
http.matchers.query
http.matchers.remote_ip
http.matchers.vars
http.matchers.vars_regexp
http.precompressed.br
http.precompressed.gzip
http.precompressed.zstd
http.reverse_proxy.selection_policies.cookie
http.reverse_proxy.selection_policies.first
http.reverse_proxy.selection_policies.header
http.reverse_proxy.selection_policies.ip_hash
http.reverse_proxy.selection_policies.least_conn
http.reverse_proxy.selection_policies.random
http.reverse_proxy.selection_policies.random_choose
http.reverse_proxy.selection_policies.round_robin
http.reverse_proxy.selection_policies.uri_hash
http.reverse_proxy.transport.fastcgi
http.reverse_proxy.transport.http
pki
tls
tls.certificates.automate
tls.certificates.load_files
tls.certificates.load_folders
tls.certificates.load_pem
tls.certificates.load_storage
tls.handshake_match.remote_ip
tls.handshake_match.sni
tls.issuance.acme
tls.issuance.internal
tls.issuance.zerossl
tls.stek.distributed
tls.stek.standard

  Standard modules: 83

layer4
layer4.handlers.echo
layer4.handlers.proxy
layer4.handlers.tee
layer4.handlers.throttle
layer4.handlers.tls
layer4.matchers.http
layer4.matchers.ip
layer4.matchers.proxy_protocol
layer4.matchers.ssh
layer4.matchers.tls
layer4.matchers.xmpp
layer4.proxy.selection_policies.first
layer4.proxy.selection_policies.ip_hash
layer4.proxy.selection_policies.least_conn
layer4.proxy.selection_policies.random
layer4.proxy.selection_policies.random_choose
layer4.proxy.selection_policies.round_robin
tls.handshake_match.alpn

  Non-standard modules: 19

  Unknown modules: 0

```

> Would love for someone to test this (@turguenev? slightly_smiling_face ) and report how they get on.

Let me know if you get stuck somewhere, I am running this exact setup currently.

**Comment by Rijul-A** [comment]
I will incorporate changes from this [discussion on Caddy forums](https://caddy.community/t/a-few-questions-about-caddyfile-converting-from-nginx-config-and-using-a-service-that-provides-its-own-certs/14433) to the PR soon. Hopefully, we should have a testing report to go along.

**Comment by mwild1** [comment]
Thanks Rijul!

**Pull request closed without merging**
